# Generated by Django 2.2.1 on 2019-06-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='yun_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
