# Generated by Django 2.2.1 on 2019-06-02 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0002_song_yun_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('familiarity', models.FloatField(blank=True, null=True)),
                ('playmeid', models.IntegerField(blank=True, null=True)),
                ('hotness', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_hotness',
            new_name='hotness',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='song',
            name='has_lyric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='release_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='musync_core.Artist'),
        ),
    ]
