# Generated by Django 2.2.1 on 2019-06-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0003_auto_20190602_1737'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
    ]
