# Generated by Django 2.2.1 on 2019-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0004_auto_20190602_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
