# Generated by Django 2.2.1 on 2019-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0006_auto_20190605_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('released_date', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.TextField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('listens', models.IntegerField(blank=True, null=True)),
                ('producer', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('tracks', models.IntegerField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.RemoveField(
            model_name='artist',
            name='familiarity',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='hotness',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='playmeid',
        ),
        migrations.AddField(
            model_name='artist',
            name='active_year_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='active_year_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='associated_labels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='comments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='favorites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='related_projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='wikipedia_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
