# Generated by Django 2.2.1 on 2019-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0008_auto_20190605_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectionListHasSong',
            new_name='CollectionListHasTrack',
        ),
        migrations.RenameModel(
            old_name='CurrentListHasSong',
            new_name='CurrentListHasTrack',
        ),
        migrations.RenameModel(
            old_name='Song',
            new_name='Track',
        ),
        migrations.RenameField(
            model_name='collectionlisthastrack',
            old_name='song',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='currentlisthastrack',
            old_name='song',
            new_name='track',
        ),
        migrations.RemoveField(
            model_name='collectionlist',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='currentlist',
            name='songs',
        ),
        migrations.AddField(
            model_name='collectionlist',
            name='tracks',
            field=models.ManyToManyField(through='musync_core.CollectionListHasTrack', to='musync_core.Track'),
        ),
        migrations.AddField(
            model_name='currentlist',
            name='tracks',
            field=models.ManyToManyField(through='musync_core.CurrentListHasTrack', to='musync_core.Track'),
        ),
        migrations.AlterModelTable(
            name='collectionlisthastrack',
            table='collection_list_has_track',
        ),
        migrations.AlterModelTable(
            name='currentlisthastrack',
            table='current_list_has_track',
        ),
        migrations.AlterModelTable(
            name='track',
            table='track',
        ),
    ]
