# Generated by Django 2.2.1 on 2019-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0009_auto_20190605_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
