# Generated by Django 2.2.1 on 2019-06-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0012_auto_20190606_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='is_cached',
            new_name='is_short_cached',
        ),
    ]
