# Generated by Django 2.2.1 on 2019-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0013_auto_20190607_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='is_cached',
            field=models.IntegerField(default=0),
        ),
    ]
