# Generated by Django 2.2.1 on 2019-06-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0015_auto_20190610_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='begin_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
