# Generated by Django 2.2.1 on 2019-06-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0017_auto_20190613_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentlisthastrack',
            name='is_playing',
            field=models.IntegerField(default=0),
        ),
    ]
