# Generated by Django 2.2.1 on 2019-06-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0018_auto_20190613_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='short_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
