# Generated by Django 2.2.1 on 2019-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0020_currentlisthastrack_is_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentlist',
            name='playing_order',
            field=models.IntegerField(default=0),
        ),
    ]
