# Generated by Django 2.2.1 on 2019-06-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musync_core', '0021_currentlist_playing_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlisthastrack',
            name='is_playing',
        ),
        migrations.RemoveField(
            model_name='currentlisthastrack',
            name='play_time',
        ),
        migrations.AddField(
            model_name='currentlist',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
